alias git='hub'
alias b='bundle-hack'
alias gh-reload='source /opt/github/env.sh'
alias gi='git'
alias ack='echo "Use ag"'
alias vi='nvim'
alias gh='p'
alias h='heroku'
alias hs='heroku sudo --reason="Debugging"'
alias ic='ion-client'
